default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("POSTGRES_USER", "troca_comigo_user") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "troca_comigo_password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>
  database: <%= ENV.fetch("POSTGRES_DB", "troca_comigo") %>

development:
  <<: *default

test:
  <<: *default
  database: troca_comigo_test

production:
  <<: *default
  database: troca_comigo_production
