version: "3.9"

services:
  backend:
    build:
      context: ./rails-backend
      dockerfile: Dockerfile
    ports:
      - "3001:80" # O Rails no container está configurado para a porta 80
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
      DATABASE_URL: postgres://user:password@db:5432/mydatabase
    volumes:
      - ./rails-backend:/rails # Sincronize o código local
    depends_on:
      - db

  frontend:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Porta padrão para o Next.js
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001 # Endereço do backend
    volumes:
      - ./nextjs-frontend:/app # Sincronize o código local

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
