version: "3.8"

services:
  backend:
    build:
      context: ./rails-backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./rails-backend:/rails
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=postgres://postgres:password@db:5432/app_development

  frontend:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-frontend:/app
    environment:
      - NODE_ENV=development

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
